### ISSUE TITLE
Серйозно?

### ISSUE THREAD

**Issue by Jeseeq** [MarinaZadoyanchuk/fp#1]
Цілий репозиторій для pipe?

**Comment by MarinaZadoyanchuk** [comment]
вау! цілий issue для того самого pipe?

**Comment by L0tso** [comment]
@savinovd диви як пайп пишется)

**Comment by savinovd** [comment]
@L0tso вау, спасибо.

**Comment by yevhenkysil** [comment]
Так так так, а что тут такое?

**Comment by MarinaZadoyanchuk** [comment]
ого, тут зібралось людей! досить таке популярне рішення 🥇
